import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import MainNavbar from "./components/MainNavbar";
import StoreProvider from "./lib/StoreProvider";
import NavbarWrapper from "./components/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vivart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider >
        <AuthProvider>
        <NavbarWrapper >
        <MainNavbar />
        {children}
        </NavbarWrapper>
        </AuthProvider>
        </StoreProvider>
        </body>
    </html>
  );
}
